#!/bin/sh
if [ -z "$__run_with_shell" ]; then
  __run_with_shell=1 exec "$SHELL" "$0" "$@"
fi

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.
set -e

if [ -z "${NVM_DIR}" ] || [ ! -d "${NVM_DIR}" ]; then
  export NVM_DIR="$HOME/.nvm"
  echo "==> Installing and activating NVM"
  curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
fi

echo "==> Installing Node LTS"
[ -s "${NVM_DIR}/nvm.sh" ] && . "${NVM_DIR}/nvm.sh" || true
nvm use --silent || nvm install --no-progress

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
  }
fi
