#!/bin/sh
if [ -z "$__run_with_shell" ]; then
  __run_with_shell=1 exec "$SHELL" "$0" "$@"
fi

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.
set -e

cd "$(dirname "$0")/.."

. script/bootstrap

"==> Installing SmartThings CLI"
npm install --global @smartthings/cli
